/*
Test generated by RoostGPT for test pom-test using AI Type Open Source AI and AI Model mistralai/Mixtral-8x7B-Instruct-v0.1

 Sure, here are some test scenarios to validate the business logic of the `init
*/

import static org.springframework.test.web.servlet.request.Mock