# ********RoostGPT********

# Test generated by RoostGPT for test hsbc-api-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /status/authorisations_post for http method type POST 
# RoostTestHash=d7fad32477
# 
# 

# ********RoostGPT********
Feature: Status Authorisations

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * configure headers = { Authorization: '#(authToken)', 'x-fapi-customer-ip-address': 'test_ip', 'x-fapi-auth-date': 'test_date', 'x-fapi-interaction-id': 'test_id', 'x-idempotency-key': 'test_key' }

Scenario Outline: Test POST method for /status/authorisations endpoint
  Given path '/status/authorisations'
  And request { merchantRequestIdentification: '<merchantRequestIdentification>', creditorAccount: { bankCode: '<bankCode>', accountIdentification: '<accountIdentification>', currency: '<currency>', accountSchemeName: '<accountSchemeName>', accountSubType: '<accountSubType>' } }
  When method post
  Then status <statusCode>
  And match response == { processResult: { responseCode: '#string', rejectReasonList: '#[]' }, mandateIdentification: '#string', mandateStatus: '#string' }

Examples:
| merchantRequestIdentification | bankCode | accountIdentification | currency | accountSchemeName | accountSubType | statusCode |
| 'test_identification'         | 'test_code' | 'test_identification' | 'test_currency' | 'test_scheme' | 'test_subtype' | 201 |
| 'test_identification'         | 'test_code' | 'test_identification' | 'test_currency' | 'test_scheme' | 'test_subtype' | 400 |
| 'test_identification'         | 'test_code' | 'test_identification' | 'test_currency' | 'test_scheme' | 'test_subtype' | 401 |
| 'test_identification'         | 'test_code' | 'test_identification' | 'test_currency' | 'test_scheme' | 'test_subtype' | 403 |
| 'test_identification'         | 'test_code' | 'test_identification' | 'test_currency' | 'test_scheme' | 'test_subtype' | 404 |
| 'test_identification'         | 'test_code' | 'test_identification' | 'test_currency' | 'test_scheme' | 'test_subtype' | 405 |
| 'test_identification'         | 'test_code' | 'test_identification' | 'test_currency' | 'test_scheme' | 'test_subtype' | 406 |
| 'test_identification'         | 'test_code' | 'test_identification' | 'test_currency' | 'test_scheme' | 'test_subtype' | 415 |
| 'test_identification'         | 'test_code' | 'test_identification' | 'test_currency' | 'test_scheme' | 'test_subtype' | 500 |
